# Title
title: Интерактивный блок

# Description (~160 symbols)
description: >
  Создание простейшего блока и добавление его в игру.
  Привязка к блоку текстур.

# Authors
authors:
  -
    name: CMTV
    github: https://github.com/CMTV
  -
    name: WildHeart
    github: https://github.com/WildsHearts